### Consultado personas
GET http://localhost:3000/api/persona/

### buscar una persona por Id.
GET http://localhost:3000/api/persona/66674643699a2e8e19631864

### creando personas
POST http://localhost:3000/api/persona/
Content-Type: application/json

{
    "Nombre":"Juana Marina",
    "Apellido":"gonzalez Olivo",
    "Telefono":"1150298544",
    "Email":"pedro@gmail.com",
    "FechaCreacion":"2024-06-08T14:35:22Z",
    "FechaActualizacion":"2024-06-08T14:35:22Z",
    "Tipo_persona":"comprador"
}

### editar persona
PUT http://localhost:3000/api/persona/66674643699a2e8e19631864
Content-Type: application/json

{
    "Nombre":"Eduardo Maria P",
    "Apellido": "Mendoza Aguilera",
    "Telefono":"1150297444",
    "Email":"eduardo@hotmail.com",
    "FechaCreacion":"2024-06-08T14:35:22Z",
    "FechaActualizacion":"2024-06-08T14:35:22Z",
    "Tipo_persona":"comprador"
}

### Eliminar una persona
DELETE  http://localhost:3000/api/persona/6667307f3c7798ed26ef5a90
