### Consultado personas
GET http://localhost:3000/api/persona/

### buscar una persona por Id.
GET http://localhost:3000/api/persona/666ae0e29006e94be77d7fda

### creando personas
POST http://localhost:3000/api/persona/
Content-Type: application/json

{
    "Nombre":"Luisa Marina borrar",
    "Apellido":"gonzalez Olivo",
    "Telefono":"1150298522",
    "Email":"luisa@gmail.com",
    "FechaCreacion":"2024-06-08T14:35:22Z",
    "FechaActualizacion":"2024-06-08T14:35:22Z",
    "Tipo_persona":"comprador"
}

### editar persona
PUT http://localhost:3000/api/persona/666ae0e29006e94be77d7fda
Content-Type: application/json

{
    "Nombre":"Eduardo Maria P",
    "Apellido": "Mendoza Aguilera",
    "Telefono":"1150297444",
    "Email":"eduardo@hotmail.com",
    "FechaCreacion":"2024-06-08T14:35:22Z",
    "FechaActualizacion":"2024-06-08T14:35:22Z",
    "Tipo_persona":"comprador"
}

### Eliminar una persona
DELETE  http://localhost:3000/api/persona/666ae1229006e94be77d7fe3
