### Consultar compradores
GET http://localhost:3000/api/comprador/

### Consultar comprador por Id
GET http://localhost:3000/api/comprador/666ae04c9006e94be77d7fc6

### Crear compradores
POST http://localhost:3000/api/comprador/
Content-Type: application/json

{
    "idauto":1,
    "idpersona":1,
    "consulta":"¿Cual es el precio de los accesorios? para borrar",
    "fechaCreacion":"2024-06-08T14:35:22Z",
    "fechaActualizacion":"2024-06-08T14:35:22Z"
}

### Editar comprador
PUT  http://localhost:3000/api/comprador/666ae04c9006e94be77d7fc6
Content-Type: application/json

{
    "idauto":2,
    "idpersona":2,
    "consulta":"Otra pregunta de nuevo",
    "fechaCreacion":"2024-06-08T14:35:22Z",
    "fechaActualizacion":"2024-06-08T14:35:22Z"
}

###
DELETE http://localhost:3000/api/comprador/666ae0899006e94be77d7fce